const GET_ROOMS = "GET_ROOMS";
const ADD_ROOM = "ADD_ROOM";
const SIGNIN = "SIGNIN";
const SIGNOUT = "SIGNOUT";
const FETCHUSERROOMS = "FETCHUSERROOMS";
const ADDUSERTOROOM = "ADDUSERTOROOM";

export { GET_ROOMS, ADD_ROOM, SIGNIN, SIGNOUT, FETCHUSERROOMS, ADDUSERTOROOM };
